/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BannerId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const DiscountType = IDL.Variant({
  'fixed' : IDL.Null,
  'percentage' : IDL.Null,
});
export const Time = IDL.Int;
export const DiscountCodeId = IDL.Nat;
export const ProductId = IDL.Nat;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const CustomerInfo = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'esewa' : IDL.Null,
  'khalti' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const Banner = IDL.Record({
  'id' : BannerId,
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageRef' : ExternalBlob,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerInfo' : CustomerInfo,
  'paymentStatus' : IDL.Bool,
  'paymentMethod' : PaymentMethod,
  'orderStatus' : OrderStatus,
  'discountApplied' : IDL.Opt(IDL.Float64),
  'createdAt' : Time,
  'updatedAt' : Time,
  'totalAmount' : IDL.Float64,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const DiscountCode = IDL.Record({
  'id' : DiscountCodeId,
  'expiresAt' : IDL.Opt(Time),
  'value' : IDL.Float64,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'minOrderAmount' : IDL.Opt(IDL.Float64),
  'maxUses' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'gender' : IDL.Text,
  'category' : CategoryId,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
  'discountedPrice' : IDL.Opt(IDL.Float64),
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBanner' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat],
      [BannerId],
      [],
    ),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
  'createDiscountCode' : IDL.Func(
      [
        IDL.Text,
        DiscountType,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Nat),
        IDL.Opt(Time),
      ],
      [DiscountCodeId],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), CustomerInfo, PaymentMethod, IDL.Opt(IDL.Float64)],
      [OrderId],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        CategoryId,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Nat,
      ],
      [ProductId],
      [],
    ),
  'deleteBanner' : IDL.Func([BannerId], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteDiscountCode' : IDL.Func([DiscountCodeId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getActiveBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getAllBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategoryById' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
  'getDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func(
      [
        IDL.Opt(CategoryId),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBanner' : IDL.Func(
      [BannerId, IDL.Text, ExternalBlob, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
  'updateDiscountCode' : IDL.Func(
      [
        DiscountCodeId,
        IDL.Text,
        DiscountType,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Nat),
        IDL.Opt(Time),
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        CategoryId,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'validateDiscountCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DiscountCode)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BannerId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const DiscountType = IDL.Variant({
    'fixed' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const Time = IDL.Int;
  const DiscountCodeId = IDL.Nat;
  const ProductId = IDL.Nat;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const CustomerInfo = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'esewa' : IDL.Null,
    'khalti' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const Banner = IDL.Record({
    'id' : BannerId,
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageRef' : ExternalBlob,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerInfo' : CustomerInfo,
    'paymentStatus' : IDL.Bool,
    'paymentMethod' : PaymentMethod,
    'orderStatus' : OrderStatus,
    'discountApplied' : IDL.Opt(IDL.Float64),
    'createdAt' : Time,
    'updatedAt' : Time,
    'totalAmount' : IDL.Float64,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const DiscountCode = IDL.Record({
    'id' : DiscountCodeId,
    'expiresAt' : IDL.Opt(Time),
    'value' : IDL.Float64,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'minOrderAmount' : IDL.Opt(IDL.Float64),
    'maxUses' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'gender' : IDL.Text,
    'category' : CategoryId,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
    'discountedPrice' : IDL.Opt(IDL.Float64),
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBanner' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat],
        [BannerId],
        [],
      ),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
    'createDiscountCode' : IDL.Func(
        [
          IDL.Text,
          DiscountType,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Nat),
          IDL.Opt(Time),
        ],
        [DiscountCodeId],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), CustomerInfo, PaymentMethod, IDL.Opt(IDL.Float64)],
        [OrderId],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          CategoryId,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Nat,
        ],
        [ProductId],
        [],
      ),
    'deleteBanner' : IDL.Func([BannerId], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteDiscountCode' : IDL.Func([DiscountCodeId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getActiveBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getAllBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategoryById' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
    'getDiscountCodes' : IDL.Func([], [IDL.Vec(DiscountCode)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func(
        [
          IDL.Opt(CategoryId),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBanner' : IDL.Func(
        [BannerId, IDL.Text, ExternalBlob, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
    'updateDiscountCode' : IDL.Func(
        [
          DiscountCodeId,
          IDL.Text,
          DiscountType,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Nat),
          IDL.Opt(Time),
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          CategoryId,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'validateDiscountCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DiscountCode)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };