/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Banner {
  'id' : BannerId,
  'title' : string,
  'linkUrl' : string,
  'displayOrder' : bigint,
  'isActive' : boolean,
  'imageRef' : ExternalBlob,
}
export type BannerId = bigint;
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
}
export type CategoryId = bigint;
export interface CustomerInfo {
  'city' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface DiscountCode {
  'id' : DiscountCodeId,
  'expiresAt' : [] | [Time],
  'value' : number,
  'code' : string,
  'discountType' : DiscountType,
  'usedCount' : bigint,
  'isActive' : boolean,
  'minOrderAmount' : [] | [number],
  'maxUses' : [] | [bigint],
}
export type DiscountCodeId = bigint;
export type DiscountType = { 'fixed' : null } |
  { 'percentage' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'customerInfo' : CustomerInfo,
  'paymentStatus' : boolean,
  'paymentMethod' : PaymentMethod,
  'orderStatus' : OrderStatus,
  'discountApplied' : [] | [number],
  'createdAt' : Time,
  'updatedAt' : Time,
  'totalAmount' : number,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'color' : string,
  'size' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'esewa' : null } |
  { 'khalti' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'sizes' : Array<string>,
  'stock' : bigint,
  'gender' : string,
  'category' : CategoryId,
  'colors' : Array<string>,
  'price' : number,
  'discountedPrice' : [] | [number],
  'images' : Array<ExternalBlob>,
}
export type ProductId = bigint;
export type Time = bigint;
export interface UserProfile {
  'city' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBanner' : ActorMethod<
    [string, ExternalBlob, string, bigint],
    BannerId
  >,
  'createCategory' : ActorMethod<[string, string], CategoryId>,
  'createDiscountCode' : ActorMethod<
    [string, DiscountType, number, [] | [number], [] | [bigint], [] | [Time]],
    DiscountCodeId
  >,
  'createOrder' : ActorMethod<
    [Array<OrderItem>, CustomerInfo, PaymentMethod, [] | [number]],
    OrderId
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      number,
      [] | [number],
      CategoryId,
      Array<string>,
      Array<string>,
      string,
      Array<ExternalBlob>,
      bigint,
    ],
    ProductId
  >,
  'deleteBanner' : ActorMethod<[BannerId], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteDiscountCode' : ActorMethod<[DiscountCodeId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getActiveBanners' : ActorMethod<[], Array<Banner>>,
  'getAllBanners' : ActorMethod<[], Array<Banner>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCategoryById' : ActorMethod<[CategoryId], [] | [Category]>,
  'getDiscountCodes' : ActorMethod<[], Array<DiscountCode>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<
    [
      [] | [CategoryId],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    Array<Product>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBanner' : ActorMethod<
    [BannerId, string, ExternalBlob, string, bigint],
    undefined
  >,
  'updateCategory' : ActorMethod<[CategoryId, string, string], undefined>,
  'updateDiscountCode' : ActorMethod<
    [
      DiscountCodeId,
      string,
      DiscountType,
      number,
      [] | [number],
      [] | [bigint],
      [] | [Time],
    ],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      number,
      [] | [number],
      CategoryId,
      Array<string>,
      Array<string>,
      string,
      Array<ExternalBlob>,
      bigint,
    ],
    undefined
  >,
  'validateDiscountCode' : ActorMethod<[string], [] | [DiscountCode]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];